- name: install k8s prereq stuff
  hosts: all
  become: true
  tasks:
    - name: install tools
      register: apt_status
      until: apt_status is success
      delay: 6
      retries: 10
      apt:
        pkg:
          - avahi-daemon
          - apt-transport-https
          - ca-certificates
          - curl
          - zsh
          - wget
          - parted
    - name: install k8s apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: install k8s apt repo
      register: repo_add
      until: repo_add is success
      delay: 6
      retries: 10
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        update_cache: yes
    - name: install k8s tools
      register: k8s_status
      until: k8s_status is success
      delay: 6
      retries: 10
      apt:
        pkg:
          - kubelet
          - kubeadm
          - kubectl
    - name: hold kubelet package
      dpkg_selections:
        name: kubelet
        selection: hold
    - name: hold kubeadm package
      dpkg_selections:
        name: kubeadm
        selection: hold
    - name: hold kubectl package
      dpkg_selections:
        name: kubectl
        selection: hold


