- name: setup my user
  hosts: all
  become: true
  tasks:
    - name: create katadmin group
      group:
        name: katadmin
        state: present
    - name: add katadmin to sudoers file
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%katadmin ALL='
        line: '%katadmin ALL=(ALL) NOPASSWD: ALL'
        validate: /usr/sbin/visudo -cf %s
    - name: add my user
      user:
        name: kat
        password_lock: yes
        comment: serena's user on pi
        append: yes
        shell: /usr/bin/zsh
        groups:
          - katadmin
    - name: drop ssh key
      authorized_key:
        user: kat
        state: present
        key: "{{ lookup('file', '/tmp/pi-image-key.pub') }}"
    - name: add my user
      user:
        name: kat-serial
        comment: serena's user on pi (only uses serial connection)
        password: "CaTxtGR/2oAFQ"
        append: yes
        shell: /usr/bin/zsh
        groups:
          - katadmin